### ISSUE TITLE
go sdk error

### ISSUE THREAD

**Issue by leidaxia** [milvus-io/milvus-sdk-go#46]
![image](https://user-images.githubusercontent.com/20982126/92377124-3baddf00-f136-11ea-8cd2-f23cd8a0b3ad.png)
我用的版本是上面标红的版本
当我使用[example](https://github.com/milvus-io/milvus-sdk-go/blob/master/examples/MilvusClientExample.go)时，报错
![image](https://user-images.githubusercontent.com/20982126/92377174-51bb9f80-f136-11ea-8aa3-86ad1d484bde.png)

**Comment by fishpenguin** [comment]
I can run the 0.4.4 sdk in my machine.
![Screenshot from 2020-09-08 15-27-22](https://user-images.githubusercontent.com/49153041/92446257-21ccd480-f1e8-11ea-98db-7bebe2393ea4.png)

And I wonder how the "Client version: v0.4.4" was printed, because there is a bug that the client version is not updated in v0.4.4.

**Comment by fishpenguin** [comment]
No more reply, I close this issue.
If you still get bugs, you can reopen this issue or open a new issue.
